Restaurants/TW/Taipei_City/Xinyi_District/restaurants.md
=> Add a great restaurant in Taiwan

Restaurants/US/California/San_Francisco/restaurants.md
woot - I hope people check this restaurant out
=> el techo sf in the mission, san francisco

Restaurants/US/California/Oakland/Restaurants.md
I've created a review of the first restaurant in Oakland, CA, which I think would be a good addition to your project. Thanks for taking a look!
(p.s. Great class. It has been very helpful)
=> first commit of Oakland Restaurants

Restaurants/US/Oregon/Portland/restaurants.md
=> Added Portland, OR

Restaurants/TW/Taiwan/Taipei/restaurants.md
Adding Sam's favorite restaurant.
=> Adding my favorite restaurant.

Restaurants/US/Texas/McKinney/restaurants.md
=> added entry for McKinney, TX

Restaurants/US/Michigan/Ann_Arbor/restaurants.md
I have added my contribution to restaurant guide - US/Michigan/Ann_Arbor
Also, is it still possible for me to sign up for your next class for free (the python learning one) even though I did not finish this in the time allowed
-Mehmed
=> mmuharem@umich.edu contributed to fromzero restaurant guide

Restaurants/AU/Western_Australia/Perth/restaurants.md
Submitting my pull request for the Udemy - The Essential Git Course project.
=> Added new restaurants.md file under AU/Western_Australia/Perth/

Restaurants/GB/London/restaurants.md
Added first London, GB restaurant. 
As London is both city and state I didn't create an extra directory, please amend if you feel this is required.
=> added first London restaurant

Restaurants/US/California/Berkeley/restaurants.md
Hello, Please review and accept the following pull request.   The git course was very helpful.
thanks,
=> Vivek's commit - adding restaurant in Berekley, CA

Restaurants/US/New_York/New_York/restaurants.md
I added the favorite restaurant of mine.
=> Marina Johnson added her favorite restaurant

Restaurants/IE/Dublin/restaurants.md
=> Added Dublin restaurant

Restaurants/US/Illinois/restaurants.md
Added Information from Chicago Restaurants
=> Added Chicago restaurant

Restaurants/US/Maryland/restaurants.md
This is me completing the final project and providing a Maryland restaurant.
=> American Restaurant in Maryland

Restaurants/ZA/Western_Cape/Cape_Town/restaurants.md
Here's a restaurant that deserves to be on this list.
=> Added Bardelli's as a restaurant in Cape Town, South Africa

Restaurants/NL/Amsterdam/restaurants.md
Greetings from Holland and I enjoyed your course!
=> Added Great Thai restaurant in Amsterdam, The Netherlands

Restaurants/CA/British_Columbia/Vancouver/restaurants.md
I think my contribution will help out the restaurant guide.
=> Added a restaurant for Vancouver, BC

Restaurants/IT/TURIN/Turin/restaurants.md
Hi,
I'm adding Italy and Turin state/province to the project
=> Add ITALY folder with a restaurant in TORINO province and Turin city

Restaurants/US/New_York/New_York/restaurants.md
=> Added the Bohemian Hall and Beer Garden in Astoria, New York

Restaurants/CA/Ontario/Ottawa/restaurant.md, Restaurants/US/Minnesota/Minneapolis/restaurants.md
Added a state from US and a province from Canada:
US - Minnesota - Minneapolis
CA - Ontario - Ottawa
=> Added couple of restaurant information, liked by me!

Restaurants/IL/tel-aviv/restaurants.md, Restaurants/IL/tel-aviv/restraunts.md
hi
i enjoyed your git course and im adding israel tel aviv restraunt
=> add tel aviv restraunt

Restaurants/PA/Panama_City/restaurants.md
I think now it´s a good addition.
=> Modified Restaurants.md on Panama (PA) Folder

Restaurants/GB/Telford/restaurants.md
Please merge this pull request.  Thoroughly enjoyed the course, may thanks Dave.
=> Thai Cuisine in Shropshire

Restaurants/TH/Bangkok/Bangkok/restaurants.md
I would like to submit the final project.  Thank you for the course.  I really enjoyed the course. Hope you make more courses and wish you the best.
=> Add a restaurant in Thailand

Restaurants/US/California/San_Francisco/restaurants.md
Thank you so much for this tutorial.
=> Added one more restaurant in San_francisco

Restaurants/US/California/San_Diego/restaurants.md
Added new city (San Diego) and restaurant
=> Created new folder San_Diego and added restaurant

Restaurants/GB/London/restaurants.md
Following your udemy tutorial request, I have added my favourite London restaurants.
=> Added two of my favourite restaurants in London

Restaurants/US/Oregon/Gresham/restaurants.md
This is a final project of your Git course on Udemy. I've added Gresham city into the Oregon folder in US directory.
=> Added the city of Gresham in Portland, Oregon (US)

Restaurants/GB/Guisborough/restaurants.md
Added my favourite Indian restaurant - I just love the food.
=> Add my favourite restaurant

Restaurants/CZ/Prague/restaurants.md
Added a restaurant in the Czech Republic, Prague
=> Added a restaurant in the Czech Republic, Prague

Restaurants/US/California/Brentwood/restaurants.md
Enjoyed the class, I learned a lot and I'm more comfortable using Git.
=> Added my favorite resturant into US/California/Brentwood

Restaurants/US/Virginia/Falls_Church/restaurants.md
Hi there - thanks for the class. I'm attempting the final project by adding one of my favorite VA pizza places. Hope I'm doing this right. Thanks!
-Jay
=> Added Lost Dog Cafe to new section: Virginia / Falls Church

Restaurants/AU/Victoria/Melbourne/restaurants.md
Thanks for the course. Has helped me develop a deeper understanding of Git.  Appreciated, Peter
=> Add a good place to eat in Australia / Melbourne

Restaurants/US/New_York/New_York/restaurants.md
=> Added Masa

Restaurants/JP/Tokyo/Chiyoda-ku/restaurants.md
I am adding a restaurant from my hometown.
=> Adding a restaurant in Tokyo

Restaurants/GB/Essex/restaurants.md
Upon course completion I have added the county Essex under GB and added my favourite restaurant to a new file for this county.
=> Added Essex in GB and added my favorite restaurant

Restaurants/BR/Ceara/Fortaleza/restaurants.md
I've just finished the git course and this is my final project. Thank you for making this amazing course, Jorge!
=> Added BR/Ceara/Fortaleza/ and my favorite restaurant

Restaurants/TW/Miaoli_City/restaurants.md
This is the best meal in my hometown
=> Add delicious Miaoli food

Restaurants/PK/Karachi/restaurants.md
Added Karachi, Pakistan - Tavern Grill
=> Added Karachi, Pakistan - Tavern Grill

Restaurants/HR/Vukovarsko_srijemska/Vukovar/restaurants.md
If you ever visit this part of world, I recommend this hotel and its restaurant.
Thanks for this creative and good way to practice fresh gained skills.
Kind regards!
=> Hello from Vukovar,Croatia

Restaurants/CA/Ontario/Toronto/restaurants.md
Added a restaurant for Toronto, Ontario, Canada. 
Apologies for the extra new lines.
=> Added Golden China Hakka restaurant for Toronto, Ontario, Canada

Restaurants/US/Nevada/Reno/restaurants.md
Added  a menu per instructions
=> add menu for reno, nv usa

Restaurants/US/Arizona/Phoenix/restaurants.md
I added a choice from my home town.  The final project was just right to help clarify some questions and reinforce the material.  I enjoyed this Udemy class. Thank you for the time to create and maintain the class. -- Alan Chudnow
=> Restaurant from Phoenix Arizona US

Restaurants/US/Michigan/New_Baltimore/restaurants.md
Trying this again.
BTW - I changed my GITHUB account name
=> Added new restaurant in New Baltimore

Restaurants/US/Arizona/Gilbert/restaurants.md
Great course on git. I hope this made it to its correct place!
=> Add my restaurant in Gilbert

Restaurants/PK/Karachi/restaurants.md
I have updated best restaurant of karachi
=> Added new restaurant of karachi

Restaurants/HU/Budapest/restaurants.md
Hi Jorge,
Please add my modification to your repo. There are no conflicts, it's able to merge automatically.
Thanks for the training at Udemy.
Best regards,
Ferenc
=> Added a restaurant for HU/Budapest

Restaurants/IN/Gujarat/Ahmedabad/restaurants.md
That's a new province to visit
=> added a new restaurant from Gujarat, IN

Restaurants/SK/Zilina/restaurants.md
=> New SK restaurant added

Restaurants/RS/Serbia/Belgrade/restaurants.md
=> Added Belgrade's best resturant

Restaurants/IL/tel-aviv/restaurants.md
I edited the IL restaurant.md file. 
Tank's for the course
=> add new resturant to IL resturant.md

Restaurants/FI/Pirkanmaa/Tampere/restaurants.md
Added folder for Finland, Pirkanmaa and Tampere and also added a restaurants.md file containing restaurant information. 
Thank you for the course, it was really helpful.
=> Added a Finnish restaurant

Restaurants/GB/Hull/restaurants.md
Hi Gorge, I have added 3 great restaurants in Hull in the UK to your restaurant guide.
Kind Regards,
Wesley Persad
=> Wesley Persad added 3 UK Hull restaurants to the guide

Restaurants/US/Florida/St_Petersburg/restaurants.md
=> Added restaurant for St Pete, FL

Restaurants/US/Massachusetts/New_Bedford/restaurants.md
I think this will be a great addition to the restaurant guide.
=> Added restaurant for New Bedford, MA

Restaurants/US/California/San_Jose/restaurants.md
=> Added my favorite restaurant in San Jose, CA, US

Restaurants/AU/South_Australia/Adelaide/restaurants.md
Thankyou for your wonderful course, it has been very helpful!
=> Added Windy Point restaurant in Adelaide, South Australia

Restaurants/DE/Baden-Württemberg/Ludwigsburg/restaurants.md
Hello Jorge,
I've just finnished your essential-git-course and added a new restaurant.
So here is my pull request.
Thank you very much!
Best Regards
Andrey
=> new restaurant in Ludwigsburg

Restaurants/UG/Entebbe/restaurants.md
=> Thai Garden - Entebbe, Uganda

Restaurants/IN/Andhra_Pradesh/Hyderabad/restaurant.md
Bawarchi welcomes world of authentic tasting biryanis and delicious North Indian cuisines. There biryani menu is well known among food lovers all over! Made with rich spices and the freshest ingredients there menu guarantees incomparable flavours and all in all a magnificent eating experience. The Bawarchi kitchen brings a huge variety of seafood delights and tandoori delicacies to brighten up day. Craving an awesome barbeque preparation? We've got it covered! Offering a range of chicken barbeque, reshmi barbeque, tandoori barbeque and the list could go on and on. So visit now and have the time
=> updating restaurant in hyderabad

Restaurants/PL/Pomorskie/Gdynia/restaurants.md
=> added great pizzeria

Restaurants/US/Illinois/Chicago/restaurants.md, Restaurants/US/Illinois/restaurants.md
In Chicago, food is your best friend.
=> Come to Chicago and We Will Treat You Right
